export type Translation = "esv" | "niv" | "kjv" | "nlt";

export type Verse = {
  ref: string;
  esv: string;
  niv: string;
  kjv: string;
  nlt: string;
};

export const VERSES: Verse[] = [
  {
    ref: "Jeremiah 29:11",
    esv: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.",
    niv: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.",
    kjv: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace, and not of evil, to give you an expected end.",
    nlt: "For I know the plans I have for you, says the Lord. They are plans for good and not for disaster, to give you a future and a hope.",
  },
  {
    ref: "Philippians 4:13",
    esv: "I can do all things through him who strengthens me.",
    niv: "I can do all this through him who gives me strength.",
    kjv: "I can do all things through Christ which strengtheneth me.",
    nlt: "For I can do everything through Christ, who gives me strength.",
  },
  {
    ref: "Romans 8:28",
    esv: "And we know that for those who love God all things work together for good, for those who are called according to his purpose.",
    niv: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.",
    kjv: "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
    nlt: "And we know that God causes everything to work together for the good of those who love God and are called according to his purpose for them.",
  },
  {
    ref: "Proverbs 3:5\u20136",
    esv: "Trust in the Lord with all your heart, and do not lean on your own understanding. In all your ways acknowledge him, and he will make straight your paths.",
    niv: "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.",
    kjv: "Trust in the Lord with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths.",
    nlt: "Trust in the Lord with all your heart; do not depend on your own understanding. Seek his will in all you do, and he will show you which path to take.",
  },
  {
    ref: "Isaiah 40:31",
    esv: "But they who wait for the Lord shall renew their strength; they shall mount up with wings like eagles; they shall run and not be weary; they shall walk and not faint.",
    niv: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.",
    kjv: "But they that wait upon the Lord shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
    nlt: "But those who trust in the Lord will find new strength. They will soar high on wings like eagles. They will run and not grow weary. They will walk and not faint.",
  },
  {
    ref: "Psalm 23:1",
    esv: "The Lord is my shepherd; I shall not want.",
    niv: "The Lord is my shepherd, I lack nothing.",
    kjv: "The Lord is my shepherd; I shall not want.",
    nlt: "The Lord is my shepherd; I have all that I need.",
  },
  {
    ref: "Matthew 6:33",
    esv: "But seek first the kingdom of God and his righteousness, and all these things will be added to you.",
    niv: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.",
    kjv: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.",
    nlt: "Seek the Kingdom of God above all else, and live righteously, and he will give you everything you need.",
  },
  {
    ref: "Joshua 1:9",
    esv: "Have I not commanded you? Be strong and courageous. Do not be frightened, and do not be dismayed, for the Lord your God is with you wherever you go.",
    niv: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.",
    kjv: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the Lord thy God is with thee whithersoever thou goest.",
    nlt: "This is my command\u2014be strong and courageous! Do not be afraid or discouraged. For the Lord your God is with you wherever you go.",
  },
  {
    ref: "Colossians 3:23",
    esv: "Whatever you do, work heartily, as for the Lord and not for men.",
    niv: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.",
    kjv: "And whatsoever ye do, do it heartily, as to the Lord, and not unto men.",
    nlt: "Work willingly at whatever you do, as though you were working for the Lord rather than for people.",
  },
  {
    ref: "Galatians 6:9",
    esv: "And let us not grow weary of doing good, for in due season we will reap, if we do not give up.",
    niv: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.",
    kjv: "And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
    nlt: "So let\u2019s not get tired of doing what is good. At just the right time we will reap a harvest of blessing if we don\u2019t give up.",
  },
  {
    ref: "2 Timothy 1:7",
    esv: "For God gave us a spirit not of fear but of power and love and self-control.",
    niv: "For the Spirit God gave us does not make us timid, but gives us power, love and self-discipline.",
    kjv: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
    nlt: "For God has not given us a spirit of fear and timidity, but of power, love, and self-discipline.",
  },
  {
    ref: "Psalm 46:10",
    esv: "Be still, and know that I am God.",
    niv: "He says, Be still, and know that I am God.",
    kjv: "Be still, and know that I am God.",
    nlt: "Be still, and know that I am God.",
  },
  {
    ref: "Lamentations 3:22\u201323",
    esv: "The steadfast love of the Lord never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.",
    niv: "Because of the Lord\u2019s great love we are not consumed, for his compassions never fail. They are new every morning; great is your faithfulness.",
    kjv: "It is of the Lord\u2019s mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.",
    nlt: "The faithful love of the Lord never ends! His mercies never cease. Great is his faithfulness; his mercies begin afresh each morning.",
  },
  {
    ref: "Isaiah 41:10",
    esv: "Fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.",
    niv: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.",
    kjv: "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
    nlt: "Don\u2019t be afraid, for I am with you. Don\u2019t be discouraged, for I am your God. I will strengthen you and help you. I will hold you up with my victorious right hand.",
  },
  {
    ref: "Philippians 4:6\u20137",
    esv: "Do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your minds in Christ Jesus.",
    niv: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.",
    kjv: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.",
    nlt: "Don\u2019t worry about anything; instead, pray about everything. Tell God what you need, and thank him for all he has done. Then you will experience God\u2019s peace, which exceeds anything we can understand. His peace will guard your hearts and minds as you live in Christ Jesus.",
  },
  {
    ref: "Ephesians 3:20",
    esv: "Now to him who is able to do far more abundantly than all that we ask or think, according to the power at work within us.",
    niv: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.",
    kjv: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us.",
    nlt: "Now all glory to God, who is able, through his mighty power at work within us, to accomplish infinitely more than we might ask or think.",
  },
  {
    ref: "Romans 12:2",
    esv: "Do not be conformed to this world, but be transformed by the renewal of your mind, that by testing you may discern what is the will of God, what is good and acceptable and perfect.",
    niv: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind. Then you will be able to test and approve what God\u2019s will is\u2014his good, pleasing and perfect will.",
    kjv: "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God.",
    nlt: "Don\u2019t copy the behavior and customs of this world, but let God transform you into a new person by changing the way you think. Then you will learn to know God\u2019s will for you, which is good and pleasing and perfect.",
  },
  {
    ref: "Matthew 11:28",
    esv: "Come to me, all who labor and are heavy laden, and I will give you rest.",
    niv: "Come to me, all you who are weary and burdened, and I will give you rest.",
    kjv: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
    nlt: "Then Jesus said, Come to me, all of you who are weary and carry heavy burdens, and I will give you rest.",
  },
  {
    ref: "Hebrews 11:1",
    esv: "Now faith is the assurance of things hoped for, the conviction of things not seen.",
    niv: "Now faith is confidence in what we hope for and assurance about what we do not see.",
    kjv: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    nlt: "Faith is the confidence that what we hope for will actually happen; it gives us assurance about things we cannot see.",
  },
  {
    ref: "Romans 15:13",
    esv: "May the God of hope fill you with all joy and peace in believing, so that by the power of the Holy Spirit you may abound in hope.",
    niv: "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.",
    kjv: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.",
    nlt: "I pray that God, the source of hope, will fill you completely with joy and peace because you trust in him. Then you will overflow with confident hope through the power of the Holy Spirit.",
  },
  {
    ref: "Psalm 37:4",
    esv: "Delight yourself in the Lord, and he will give you the desires of your heart.",
    niv: "Take delight in the Lord, and he will give you the desires of your heart.",
    kjv: "Delight thyself also in the Lord; and he shall give thee the desires of thine heart.",
    nlt: "Take delight in the Lord, and he will give you your heart\u2019s desires.",
  },
  {
    ref: "Proverbs 16:3",
    esv: "Commit your work to the Lord, and your plans will be established.",
    niv: "Commit to the Lord whatever you do, and he will establish your plans.",
    kjv: "Commit thy works unto the Lord, and thy thoughts shall be established.",
    nlt: "Commit your actions to the Lord, and your plans will succeed.",
  },
  {
    ref: "1 Corinthians 16:13",
    esv: "Be watchful, stand firm in the faith, act like men, be strong.",
    niv: "Be on your guard; stand firm in the faith; be courageous; be strong.",
    kjv: "Watch ye, stand fast in the faith, quit you like men, be strong.",
    nlt: "Be on guard. Stand firm in the faith. Be courageous. Be strong.",
  },
  {
    ref: "James 1:2\u20134",
    esv: "Count it all joy, my brothers, when you meet trials of various kinds, for you know that the testing of your faith produces steadfastness. And let steadfastness have its full effect, that you may be perfect and complete, lacking in nothing.",
    niv: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance. Let perseverance finish its work so that you may be mature and complete, not lacking anything.",
    kjv: "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience. But let patience have her perfect work, that ye may be perfect and entire, wanting nothing.",
    nlt: "Dear brothers and sisters, when troubles of any kind come your way, consider it an opportunity for great joy. For you know that when your faith is tested, your endurance has a chance to grow. So let it grow, for when your endurance is fully developed, you will be perfect and complete, needing nothing.",
  },
  {
    ref: "1 Peter 5:7",
    esv: "Casting all your anxieties on him, because he cares for you.",
    niv: "Cast all your anxiety on him because he cares for you.",
    kjv: "Casting all your care upon him; for he careth for you.",
    nlt: "Give all your worries and cares to God, for he cares about you.",
  },
  {
    ref: "Proverbs 18:10",
    esv: "The name of the Lord is a strong tower; the righteous man runs into it and is safe.",
    niv: "The name of the Lord is a fortified tower; the righteous run to it and are safe.",
    kjv: "The name of the Lord is a strong tower: the righteous runneth into it, and is safe.",
    nlt: "The name of the Lord is a strong fortress; the godly run to him and are safe.",
  },
  {
    ref: "Deuteronomy 31:6",
    esv: "Be strong and courageous. Do not fear or be in dread of them, for it is the Lord your God who goes with you. He will not leave you or forsake you.",
    niv: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you; he will never leave you nor forsake you.",
    kjv: "Be strong and of a good courage, fear not, nor be afraid of them: for the Lord thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.",
    nlt: "So be strong and courageous! Do not be afraid and do not panic before them. For the Lord your God will personally go ahead of you. He will neither fail you nor abandon you.",
  },
  {
    ref: "John 3:16",
    esv: "For God so loved the world, that he gave his only Son, that whoever believes in him should not perish but have eternal life.",
    niv: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.",
    kjv: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    nlt: "For this is how God loved the world: He gave his one and only Son, so that everyone who believes in him will not perish but have eternal life.",
  },
  {
    ref: "Romans 5:8",
    esv: "But God shows his love for us in that while we were still sinners, Christ died for us.",
    niv: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.",
    kjv: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.",
    nlt: "But God showed his great love for us by sending Christ to die for us while we were still sinners.",
  },
  {
    ref: "Revelation 21:4",
    esv: "He will wipe away every tear from their eyes, and death shall be no more, neither shall there be mourning, nor crying, nor pain anymore, for the former things have passed away.",
    niv: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain, for the old order of things has passed away.",
    kjv: "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away.",
    nlt: "He will wipe every tear from their eyes, and there will be no more death or sorrow or crying or pain. All these things are gone forever.",
  },
];
